apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: example
spec:
  version: {{ .TagName }}
  homepage: https://github.com/talos-labs/kubectl-example
  shortDescription: Prints out example manifest YAMLs
  description: |
    Prints out a example manifest YAML for a given resource type.
    The plugin works similar to a dry run output but for arbitrary resources.
    All examples originate from kubernetes.io.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/talos-labs/kubectl-example/releases/download/{{ .TagName }}/kubectl-example_Darwin_arm64.tar.gz" .TagName }}
    bin: "./kubectl-example"
    files:
      - from: kubectl-example
        to: .
      - from: LICENSE
        to: .
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/talos-labs/kubectl-example/releases/download/{{ .TagName }}/kubectl-example_Darwin_x86_64.tar.gz" .TagName }}
    bin: "./kubectl-example"
    files:
      - from: kubectl-example
        to: .
      - from: LICENSE
        to: .
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/talos-labs/kubectl-example/releases/download/{{ .TagName }}/kubectl-example_Linux_arm64.tar.gz" .TagName }}
    bin: "./kubectl-example"
    files:
      - from: kubectl-example
        to: .
      - from: LICENSE
        to: .
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/talos-labs/kubectl-example/releases/download/{{ .TagName }}/kubectl-example_Linux_x86_64.tar.gz" .TagName }}
    bin: "./kubectl-example"
    files:
      - from: kubectl-example
        to: .
      - from: LICENSE
        to: .
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/talos-labs/kubectl-example/releases/download/{{ .TagName }}/kubectl-example_Windows_x86_64.zip" .TagName }}
    bin: "./kubectl-example.exe"
    files:
      - from: kubectl-example.exe
        to: .
      - from: LICENSE
        to: .
